### ISSUE TITLE
Going through a teleporter changes the angle of movement

### ISSUE THREAD

**Issue by drakfyre** [DrBeef/QuestZDoom#1]
If you travel through a teleporter and there's a difference between your entry and exit angles, the angle of movement on the left stick will be skewed.  Using the right stick to rotate fixes the problem, but it is disorienting before that.

**Comment by Reichstein01** [comment]
Just chiming in to add some detail to this issue.

It seem that when the player is teleported their movement direction is changed by the teleporter (as is normal for Doom) however the player's view direction is not adjusted.

Resetting the view direction to match the movement direction on teleport could be a potential fix.

**Comment by smklancher** [comment]
I'm using teleport locomotion and after going through a teleporter, the third person Doom-Guy is looking in the direction changed by the teleporter instead of forward.  And then when trying to use switches/doors, I cannot just look forward at it, but have to adjust in accordance with the direction the third person Doom-Guy is looking.

I'm sure this is exactly what has already been described, but just wanted to add the details of what a player sees when using teleport locomotion.

**Comment by DrBeef** [comment]
Thanks everyone. I know what the issue is and have already fixed it for the next patch release (v1.0.1).
