### ISSUE TITLE
Simon's Destiny not detected

### ISSUE THREAD

**Issue by bferguson3** [DrBeef/QuestZDoom#7]
Awesome work so far, been having a blast.

Unfortunately one mod I've tried to play, Simon's Destiny, doesn't seem to be recognized. I haven't tried launching it with a manual command yet, but it would be great if this had native support (like Hocus Pocus!)

Thanks!

**Comment by baggyg** [comment]
Can you elaborate? Presumably you have put the wad file in the mods directory... does it not show in the "other" section?

**Comment by bferguson3** [comment]
Hi Grant,

Thanks for replying. So the problem is twofold, turns out:
1. Simon's Destiny is actually an *.ipk3, which is some zdoom modified pk3
format which includes some extra information (not entirely sure). Looks
like the launcher only looks for *.pk3.
2. Renaming the ipk3 to pk3 gets it to display in the zdoom launcher, but
attempting to start it up crashes to home.

https://forum.zdoom.org/viewtopic.php?t=57800

Let me know what else I can do to help test.

**Comment by baggyg** [comment]
1. You assumption here is incorrect according to the code:
private string[] coreGameExtensions = { ".wad", ".ipk3", ".ipk7", ".iwad", ".pk3", ".pk7", ".deh" };
private string[] modExtensions = { ".zip", ".ipk3", ".pk3", ".wad", ".iwad", ".pk7", ".ipk7", ".deh" };

are allowed. Make sure you have the latest version of the launcher installed as this did change in on of the releases. 

2. With it correctly labelled as a ipk3, see if it now loads. 

Looking at the page, this should actually be put in the wads folder since it doesn't need a core game to function: 

* Standalone? So i don't need Doom2 to run it, right?
Correct! Just grab Gzdoom, drop Castlevania.ipk3 in and you're ready to start your quest!

I've actually played this so I know it does work.

**Comment by bferguson3** [comment]
You're correct - I was on the most recent version and it was in the wads folder, but it was apparently a corrupted version of the ipk3 somehow! I redownloaded it and it works.

Thanks! (closing)
